[graph]
all-features = true

[advisories]
version = 2
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"

[licenses]
version = 2
allow = [
    "AGPL-3.0-or-later",
    "Apache-2.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"

[[bans.skip]]
name = "syn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
