[package]
name = "wikinext-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "wikinext"
path = "src/main.rs"

[dependencies]
wikinext-app.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
